[package]
name = "engine"
version = "0.1.0"
authors = []
edition = "2021"
description = ""
documentation = ""
readme = false
homepage = ""
repository = ""
license = ""
publish = false
autobenches = false

[lib]
crate_type = ["cdylib", "rlib"]