[workspace]
members = [
    "xevm_engine_rs/engine",
    "xevm_engine_rs/engine-precompiles",
    "xevm_engine_rs/engine-sdk",
    "xevm_engine_rs/engine-transactions",
    "xevm_engine_rs/engine-types",
]